"""delete playlist field from rankings

Revision ID: a962a44a7eb9
Revises: 
Create Date: 2018-04-16 15:03:31.576027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a962a44a7eb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_playlist')
    op.drop_constraint('rankings_playlistID_fkey', 'rankings', type_='foreignkey')
    op.drop_column('rankings', 'playlistID')
    op.add_column('song_rankings', sa.Column('ranking_id', sa.Integer(), nullable=True))
    op.drop_constraint('song_rankings_user_id_fkey', 'song_rankings', type_='foreignkey')
    op.drop_constraint('song_rankings_playlist_id_fkey', 'song_rankings', type_='foreignkey')
    op.drop_constraint('song_rankings_rank_id_fkey', 'song_rankings', type_='foreignkey')
    op.create_foreign_key(None, 'song_rankings', 'rankings', ['ranking_id'], ['id'])
    op.drop_column('song_rankings', 'playlist_id')
    op.drop_column('song_rankings', 'rank_id')
    op.drop_column('song_rankings', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song_rankings', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('song_rankings', sa.Column('rank_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('song_rankings', sa.Column('playlist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'song_rankings', type_='foreignkey')
    op.create_foreign_key('song_rankings_rank_id_fkey', 'song_rankings', 'rankings', ['rank_id'], ['id'])
    op.create_foreign_key('song_rankings_playlist_id_fkey', 'song_rankings', 'playlists', ['playlist_id'], ['id'])
    op.create_foreign_key('song_rankings_user_id_fkey', 'song_rankings', 'users', ['user_id'], ['id'])
    op.drop_column('song_rankings', 'ranking_id')
    op.add_column('rankings', sa.Column('playlistID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('rankings_playlistID_fkey', 'rankings', 'playlists', ['playlistID'], ['id'])
    op.create_table('user_playlist',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('playlist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name='user_playlist_playlist_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_playlist_user_id_fkey')
    )
    # ### end Alembic commands ###
